### ISSUE TITLE
Jenkins: investigate jenkins slave on Mac headless issue when user not logged in

### ISSUE THREAD

**Issue by ahouben** [Greenliff/SwissmomiOS#4]
For the smoke test on the simulator

**Comment by green-mdoerflinger** [comment]
I assume the simulator is missing any X-DISPLAY.  
You could try to run a Xvfb (X virtual frame buffer) which emulates a X-framework without actually showing it. The Xvfb would have to be started before starting the test. 

https://en.wikipedia.org/wiki/Xvfb

**Comment by green-mdoerflinger** [comment]
Does the iOS emulator have some kind of no-window mode?

**Comment by ihirt** [comment]
- MacOs doesn't come with X11, but with Apple's Quartz. I didn't find any virtual frame buffer for Quartz.
- xvfb is not working on MacOs because it only supports X11
- The iOS simulator doesn't support a headless mode

I didn't find any solution to use the jenkins slave via ssh for UITests without having logged in the jenkins user.

I ended up to add auto login to the jenkins user on the Mac when the machine boots. Thus, the jenkins user should net be logged off.
